# Generated by Django 5.0.2 on 2024-02-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseaccess',
            name='access_start_time',
        ),
    ]
