# Generated by Django 5.0.2 on 2024-02-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0002_remove_databaseaccess_access_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseaccess',
            name='database_access_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
