# Generated by Django 5.0.2 on 2024-02-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0003_databaseaccess_database_access_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseaccess',
            name='granted_database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='databaseaccess',
            name='access_status',
            field=models.CharField(choices=[('Granted', 'Granted'), ('Closed', 'Closed')], default='Granted', max_length=20),
        ),
    ]
