# Generated by Django 5.0.2 on 2024-02-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0005_databaseaccess_access_time_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseaccess',
            name='access_db_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
