# Generated by Django 5.0.2 on 2024-02-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0007_alter_databaseaccess_access_give_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='access_given_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
