# Generated by Django 5.0.2 on 2024-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0008_alter_databaseaccess_access_given_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseaccess',
            name='access_given_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
