# Generated by Django 5.0.2 on 2024-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0009_databaseaccess_access_given_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseaccess',
            name='access_closed_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
