# Generated by Django 5.0.2 on 2024-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0012_alter_databaseaccess_access_closed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseaccess',
            name='access_closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
