# Generated by Django 5.0.2 on 2024-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0013_alter_databaseaccess_access_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseaccess',
            name='granted_database2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
